version: '2'
services:
  xserver:
    image: devrt/xserver
    ports:
      - "3000:80"
  workspace:
    # env_file:
    #   - .env
    image: devrt/ros-devcontainer-vscode
    ports:
      - "3001:3000"
    volumes:
      - workspace:/workspace
      - ~/.gitconfig:/home/developer/.gitconfig
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
    volumes_from:
      - xserver
    depends_on:
      - xserver
volumes:
  workspace:
